version: '3'
services:
  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000'
    volumes:
      - ./client:/react-app
      - /react-app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - mern-network
  server:
    build: ./server
    container_name: server_c
    ports:
      - '5000'
    volumes:
      - ./server:/node-app
      - /node-app/node_modules
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge